[package]
name = "echostream-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
description = "核心框架：RPC / Event / Stream 调度、会话管理与服务端客户端实现"

[dependencies]
echostream-proto = { workspace = true }
echostream-transport = { workspace = true }

tokio = { workspace = true }
postcard = { workspace = true }
serde = { workspace = true }
bytes = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
