/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_clientcorehandle_free: (a: number, b: number) => void;
export const clientcorehandle_build_datagram_event: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const clientcorehandle_build_error_response: (a: number, b: number, c: bigint, d: number, e: number) => void;
export const clientcorehandle_build_event: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const clientcorehandle_build_response: (a: number, b: number, c: bigint, d: number, e: number) => void;
export const clientcorehandle_build_stream_end: (a: number, b: number, c: bigint) => void;
export const clientcorehandle_build_stream_frame: (a: number, b: number, c: bigint, d: number, e: number, f: number, g: number, h: bigint) => void;
export const clientcorehandle_handle_inbound: (a: number, b: number, c: number, d: number) => void;
export const clientcorehandle_new: () => number;
export const clientcorehandle_on_event: (a: number, b: number, c: number, d: number) => void;
export const clientcorehandle_on_rpc: (a: number, b: number, c: number, d: number) => void;
export const clientcorehandle_on_stream: (a: number, b: number, c: number, d: number) => void;
export const clientcorehandle_open_stream: (a: number, b: number, c: number) => bigint;
export const clientcorehandle_request: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const decode_bytes: (a: number, b: number, c: number) => void;
export const decode_i64: (a: number, b: number, c: number) => void;
export const decode_message: (a: number, b: number, c: number) => void;
export const decode_payload: (a: number, b: number, c: number, d: number) => void;
export const decode_string: (a: number, b: number, c: number) => void;
export const decode_u64: (a: number, b: number, c: number) => void;
export const encode_frame: (a: number, b: number) => void;
export const encode_i64: (a: number, b: bigint) => void;
export const encode_message: (a: number, b: number) => void;
export const encode_payload: (a: number, b: number) => void;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export3: (a: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_export4: (a: number, b: number, c: number) => void;
